---
kind: pipeline
type: vm
name: testing

platform:
  os: linux
  arch: amd64

pool:
  use: ubuntu

steps:
- name: vet
  image: golang:1.17.3
  commands:
  - go vet ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: test
  image: golang:1.17.3
  commands:
  - go test -cover ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
type: vm
name: windows-ltsc2022-docker

platform:
  os: windows

pool:
  use: windows-2022

steps:
- name: build_latest
  image: golang:1.18
  environment:
    VERSION: ltsc2022
    REGISTRY: docker
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_tag
  image: golang:1.18
  environment:
    VERSION: ltsc2022
    REGISTRY: docker
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
  - testing

---
kind: pipeline
name: manifest-docker

platform:
  os: linux
  arch: amd64

pool:
  use: ubuntu

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/docker/manifest.tmpl
    username:
      from_secret: docker_username

depends_on:
- windows-ltsc2022-docker
